# Docker Pipeline build steps
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
name: $(Build.BuildId)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyy-MM-dd)
trigger:
    batch: true
    branches:
     include:
       - develop
  
  #resources:
  #- repo: self
  
  #variables:
  #  tag: '$(Build.BuildId)'
  
stages:
 - stage: dockerBuild 
   #displayName: Docker build
   jobs:  
   - job: dockerBuildJob
     #displayName: Docker Build
     timeoutInMinutes: 10
     pool:
       vmImage: 'ubuntu-latest'
     steps:
     - task: Docker@2
       displayName: Build Docker
       inputs:
         containerRegistry: 'ICAV_Azure_Container_Registry'
         repository: 'icavtech-challenge'
         command: buildAndPush
         dockerfile: 'icavtech-challenge/Dockerfile'
         tags: |
           v1.0.0.$(Build.BuildId)
 - stage: k8deploy 
   #displayName: K8 Deployment
   jobs:  
   - job: k8deployJob
     displayName: k8 Deployment Build
     timeoutInMinutes: 10
     pool: 
       vmImage: 'ubuntu-latest'
     steps:
     - task: KubernetesManifest@0
       displayName: create secert
       inputs:
         action: 'createSecret'
         kubernetesServiceConnection: 'ICAV_Azure_K8'
         namespace: 'default'
         secretType: 'dockerRegistry'
         secretName: 'regcred'
         dockerRegistryEndpoint: 'ICAV_Azure_Container_Registry'
     - task: KubernetesManifest@0
       displayName: Deploy manifest file
       inputs:
         action: 'deploy'
         kubernetesServiceConnection: 'ICAV_Azure_K8'
         namespace: 'default'
         manifests: 'icavtech-challenge/manifest.yml'
         containers: 'icavtechicontainer/icavtech-challenge:v1.0.0.$(Build.BuildId)'
         imagePullSecrets: 'regcred'
      